In [1]:
import pandas as pd

In [2]:
import data_fusion_transformation as dft
from data_preprocessing import datetime_format

def init_dt(dt_str):
	return dft.init_date_object(dt_str, datetime_format)

In [3]:
df = pd.read_csv('preprocessed_471.csv')

In [4]:
df

                       Date   Speed
0       2017-01-01 00:00:00   86.50
1       2017-01-01 00:05:00   91.00
2       2017-01-01 00:10:00   -1.00
3       2017-01-01 00:15:00   -1.00
4       2017-01-01 00:20:00   -1.00
5       2017-01-01 00:25:00   -1.00
6       2017-01-01 00:30:00   -1.00
7       2017-01-01 00:35:00   -1.00
8       2017-01-01 00:40:00   -1.00
9       2017-01-01 00:45:00   -1.00
10      2017-01-01 00:50:00   -1.00
11      2017-01-01 00:55:00   -1.00
12      2017-01-01 01:00:00   -1.00
13      2017-01-01 01:05:00   90.00
14      2017-01-01 01:10:00   92.25
15      2017-01-01 01:15:00   91.75
16      2017-01-01 01:20:00   93.40
17      2017-01-01 01:25:00   91.20
18      2017-01-01 01:30:00   92.20
19      2017-01-01 01:35:00   91.80
20      2017-01-01 01:40:00   91.00
21      2017-01-01 01:45:00   90.80
22      2017-01-01 01:50:00   90.00
23      2017-01-01 01:55:00   87.40
24      2017-01-01 02:00:00   90.80
25      2017-01-01 02:05:00   89.00
26      2017-01-01 02:10:00   88.80
27      2017-01-01 02:15:00   86.20
28      2017-01-01 02:20:00   87.00
29      2017-01-01 02:25:00   89.60
...                     ...     ...
104827  2017-12-30 23:35:00   96.75
104828  2017-12-30 23:40:00   97.50
104829  2017-12-30 23:45:00   98.00
104830  2017-12-30 23:50:00   97.00
104831  2017-12-30 23:55:00   98.40
104832  2017-12-31 00:00:00   98.60
104833  2017-12-31 00:05:00   98.00
104834  2017-12-31 00:10:00   97.00
104835  2017-12-31 00:15:00   96.20
104836  2017-12-31 00:20:00   98.20
104837  2017-12-31 00:25:00   99.80
104838  2017-12-31 00:30:00   99.00
104839  2017-12-31 00:35:00   99.80
104840  2017-12-31 00:40:00   98.00
104841  2017-12-31 00:45:00  100.00
104842  2017-12-31 00:50:00   99.00
104843  2017-12-31 00:55:00   99.60
104844  2017-12-31 01:00:00  101.00
104845  2017-12-31 01:05:00  101.60
104846  2017-12-31 01:10:00  100.20
104847  2017-12-31 01:15:00  100.20
104848  2017-12-31 01:20:00   96.60
104849  2017-12-31 01:25:00  102.40
104850  2017-12-31 01:30:00  103.80
104851  2017-12-31 01:35:00  105.00
104852  2017-12-31 01:40:00  103.00
104853  2017-12-31 01:45:00  101.80
104854  2017-12-31 01:50:00  102.25
104855  2017-12-31 01:55:00  103.60
104856  2017-12-31 02:00:00  103.25

[104857 rows x 2 columns]

In [5]:
def init_dt(dt_str):
	return dft.init_date_object(dt_str, datetime_format)

In [44]:
df['dt'] = df['Date'].apply(init_dt)
df.drop(['Date'], axis = 'columns', inplace = True)

In [7]:
df.columns

Index(['Speed', 'dt'], dtype='object')

In [14]:
df['dt'].dtype

dtype('<M8[ns]')

In [45]:
df.set_index(['dt'], inplace = True)

In [18]:
df.index.values

array(['2017-01-01T00:00:00.000000000', '2017-01-01T00:05:00.000000000',
       '2017-01-01T00:10:00.000000000', ...,
       '2017-12-31T01:50:00.000000000', '2017-12-31T01:55:00.000000000',
       '2017-12-31T02:00:00.000000000'], dtype='datetime64[ns]')

In [19]:
df['dt']

KeyError: 'dt'

In [20]:
df

                      Speed
dt
2017-01-01 00:00:00   86.50
2017-01-01 00:05:00   91.00
2017-01-01 00:10:00   -1.00
2017-01-01 00:15:00   -1.00
2017-01-01 00:20:00   -1.00
2017-01-01 00:25:00   -1.00
2017-01-01 00:30:00   -1.00
2017-01-01 00:35:00   -1.00
2017-01-01 00:40:00   -1.00
2017-01-01 00:45:00   -1.00
2017-01-01 00:50:00   -1.00
2017-01-01 00:55:00   -1.00
2017-01-01 01:00:00   -1.00
2017-01-01 01:05:00   90.00
2017-01-01 01:10:00   92.25
2017-01-01 01:15:00   91.75
2017-01-01 01:20:00   93.40
2017-01-01 01:25:00   91.20
2017-01-01 01:30:00   92.20
2017-01-01 01:35:00   91.80
2017-01-01 01:40:00   91.00
2017-01-01 01:45:00   90.80
2017-01-01 01:50:00   90.00
2017-01-01 01:55:00   87.40
2017-01-01 02:00:00   90.80
2017-01-01 02:05:00   89.00
2017-01-01 02:10:00   88.80
2017-01-01 02:15:00   86.20
2017-01-01 02:20:00   87.00
2017-01-01 02:25:00   89.60
...                     ...
2017-12-30 23:35:00   96.75
2017-12-30 23:40:00   97.50
2017-12-30 23:45:00   98.00
2017-12-30 23:50:00   97.00
2017-12-30 23:55:00   98.40
2017-12-31 00:00:00   98.60
2017-12-31 00:05:00   98.00
2017-12-31 00:10:00   97.00
2017-12-31 00:15:00   96.20
2017-12-31 00:20:00   98.20
2017-12-31 00:25:00   99.80
2017-12-31 00:30:00   99.00
2017-12-31 00:35:00   99.80
2017-12-31 00:40:00   98.00
2017-12-31 00:45:00  100.00
2017-12-31 00:50:00   99.00
2017-12-31 00:55:00   99.60
2017-12-31 01:00:00  101.00
2017-12-31 01:05:00  101.60
2017-12-31 01:10:00  100.20
2017-12-31 01:15:00  100.20
2017-12-31 01:20:00   96.60
2017-12-31 01:25:00  102.40
2017-12-31 01:30:00  103.80
2017-12-31 01:35:00  105.00
2017-12-31 01:40:00  103.00
2017-12-31 01:45:00  101.80
2017-12-31 01:50:00  102.25
2017-12-31 01:55:00  103.60
2017-12-31 02:00:00  103.25

[104857 rows x 1 columns]

In [22]:
print(type(df.index))

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>

In [23]:
df.index.month

Int64Index([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
            ...
            12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
           dtype='int64', name='dt', length=104857)

In [24]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0, 1))

In [47]:
missing = df[df['Speed'] == -1]

In [48]:
missing.groupby(missing.index.month).count()

    Speed
dt
1      11
2    1131
3    1897
6       1
7       2
8      55
10      2
11     50
12    112

In [38]:
data = df[df.index.month == 5]

In [40]:
data[data['Speed'] == -1]

Empty DataFrame
Columns: [Speed]
Index: []

In [37]:
df['2017-04-25 22:10:00']

KeyError: '2017-04-25 22:10:00'

In [42]:
df = pd.read_csv("preprocessed_471.csv")

In [46]:
df

                      Speed
dt
2017-01-01 00:00:00   86.50
2017-01-01 00:05:00   91.00
2017-01-01 00:10:00   -1.00
2017-01-01 00:15:00   -1.00
2017-01-01 00:20:00   -1.00
2017-01-01 00:25:00   -1.00
2017-01-01 00:30:00   -1.00
2017-01-01 00:35:00   -1.00
2017-01-01 00:40:00   -1.00
2017-01-01 00:45:00   -1.00
2017-01-01 00:50:00   -1.00
2017-01-01 00:55:00   -1.00
2017-01-01 01:00:00   -1.00
2017-01-01 01:05:00   90.00
2017-01-01 01:10:00   92.25
2017-01-01 01:15:00   91.75
2017-01-01 01:20:00   93.40
2017-01-01 01:25:00   91.20
2017-01-01 01:30:00   92.20
2017-01-01 01:35:00   91.80
2017-01-01 01:40:00   91.00
2017-01-01 01:45:00   90.80
2017-01-01 01:50:00   90.00
2017-01-01 01:55:00   87.40
2017-01-01 02:00:00   90.80
2017-01-01 02:05:00   89.00
2017-01-01 02:10:00   88.80
2017-01-01 02:15:00   86.20
2017-01-01 02:20:00   87.00
2017-01-01 02:25:00   89.60
...                     ...
2017-12-30 23:35:00   96.75
2017-12-30 23:40:00   97.50
2017-12-30 23:45:00   98.00
2017-12-30 23:50:00   97.00
2017-12-30 23:55:00   98.40
2017-12-31 00:00:00   98.60
2017-12-31 00:05:00   98.00
2017-12-31 00:10:00   97.00
2017-12-31 00:15:00   96.20
2017-12-31 00:20:00   98.20
2017-12-31 00:25:00   99.80
2017-12-31 00:30:00   99.00
2017-12-31 00:35:00   99.80
2017-12-31 00:40:00   98.00
2017-12-31 00:45:00  100.00
2017-12-31 00:50:00   99.00
2017-12-31 00:55:00   99.60
2017-12-31 01:00:00  101.00
2017-12-31 01:05:00  101.60
2017-12-31 01:10:00  100.20
2017-12-31 01:15:00  100.20
2017-12-31 01:20:00   96.60
2017-12-31 01:25:00  102.40
2017-12-31 01:30:00  103.80
2017-12-31 01:35:00  105.00
2017-12-31 01:40:00  103.00
2017-12-31 01:45:00  101.80
2017-12-31 01:50:00  102.25
2017-12-31 01:55:00  103.60
2017-12-31 02:00:00  103.25

[104857 rows x 1 columns]

In [52]:
training_set = df.iloc[:, :1].values

In [53]:
training_set_scaled = sc.fit_transform(training_set)

training_set

In [56]:
training_set

array([[ 86.5 ],
       [ 91.  ],
       [ -1.  ],
       ...,
       [102.25],
       [103.6 ],
       [103.25]])